### ISSUE TITLE
建议楼主在项目栏名字或介绍里加上madvr的字样

### ISSUE THREAD

**Issue by SuTree** [revaraver/Soft-CHS#2]
RT,一时想不起来地址，搜github也没有答案，搜谷歌到vsb才找到。

**Comment by revaraver** [comment]
> RT,一时想不起来地址，搜github也没有答案，搜谷歌到vsb才找到。

有道理,我已经加上了,madvr+汉化 关键字就能精确定位

**Comment by SuTree** [comment]
done
